### ISSUE TITLE
 is it possible to translate the tips(eg: password)

### ISSUE THREAD

**Issue by ffs-akl** [birbkeks/win10-sddm-theme#1]
I'm not an English speaking user, is it possible to translate the information in there like “password” into my native language?

**Comment by ffs-akl** [comment]
by added someting to theme.conf and components, I have translated all of tips but date and  tip of  button of login.   
How to translate the both, please help.

**Comment by syrupderg** [comment]
> I'm not an English speaking user, is it possible to translate the information in there like “password” into my native language?

absolutely! what is your main language? 

> by added someting to theme.conf and components, I have translated all of tips but date and tip of button of login.
> How to translate the both, please help.

If you're asking for the tooltip text of the login button next to the password field, check UserPanel.qml 141 line.
![image](https://github.com/birbkeks/win10-sddm-theme/assets/67545942/ae2f37c8-1f14-4cd6-a451-6610c7daa05d)

ill add translations for other languages in the future but not planned when.

**Comment by ffs-akl** [comment]
Thank you for help!
My main language is zh_CN.
for the date,  I added the` Locale="zh_CN.UTF-8"` to theme.conf, but didn't take effect.
by the way,  the Capslock  Warning  didn't work.   Is it working on wayland?

**Comment by syrupderg** [comment]
>  I added the` Locale="zh_CN.UTF-8"` to theme.conf,

yes because i didnt coded text to work with translation stuff

> Capslock Warning didn't work. Is it working on wayland?

its both working on x11 and wayland for me (i dont think thats a x11 or wayland issue)

**Comment by ffs-akl** [comment]
>yes because i didnt coded text to work with translation stuff

I have added  something like "new Date().toLocaleDateString" to main.qml, and  It worked fine with `Locale="zh_CN.UTF-8"` in theme.conf.

>its both working on x11 and wayland for me (i dont think thats a x11 or wayland issue)

I note that there's a button at the left of the session button.  it should be the caps warning button, but it doesn't show up for me, and it was able to be  clicked by mouse, but didn't respond.  

My environment is VMWARE+ARCH+LABWC+LXQT(wayland Seesion), is there anything I need to configure specifically?

**Comment by syrupderg** [comment]
> I note that there's a button at the left of the session button. it should be the caps warning button, but it doesn't show up for me, and it was able to be clicked by mouse, but didn't respond.

can you send a screenshot of it?

**Comment by ffs-akl** [comment]
Please refer to the following photo.  
for hover
<img width="422" alt="hover" src="https://github.com/birbkeks/win10-sddm-theme/assets/166389780/d44e8e93-696a-4d4a-b397-2f4939994896">

for click
<img width="440" alt="click" src="https://github.com/birbkeks/win10-sddm-theme/assets/166389780/6fc34642-53a0-43a1-86c6-9768d1f4bb4d">

**Comment by syrupderg** [comment]
> Please refer to the following photo. for hover <img alt="hover" width="422" src="https://private-user-images.githubusercontent.com/166389780/346636798-d44e8e93-696a-4d4a-b397-2f4939994896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjkyNTksIm5iZiI6MTcyMDUyODk1OSwicGF0aCI6Ii8xNjYzODk3ODAvMzQ2NjM2Nzk4LWQ0NGU4ZTkzLTY5NmEtNGQ0YS1iMzk3LTJmNDkzOTk5NDg5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2EyNGM5MjFlNzFlMjhiMTdiYzUxZDk4NDI1NmIzMjE1ZGM5Y2I0MGVhYjMxZjE0ZWQxMTllYTMwNDhmM2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SrJfk2xJnSKnPQg59udwBP-bHHVXVOuGujgYGIhUMNY">
> 
> for click <img alt="click" width="440" src="https://private-user-images.githubusercontent.com/166389780/346636825-6fc34642-53a0-43a1-86c6-9768d1f4bb4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjkyNTksIm5iZiI6MTcyMDUyODk1OSwicGF0aCI6Ii8xNjYzODk3ODAvMzQ2NjM2ODI1LTZmYzM0NjQyLTUzYTAtNDNhMS04NmM2LTk3NjhkMWY0YmI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTYxNDE3MWJjNjRmMTYwYjVhMDIwM2ZmNmJjYmM2MDA4MTg5OTVjMzEwYzVjMjQ4M2MzMDgxMjdiZjMwYTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZHtJNXI-8CdTpd83RowHjQVEqJ14ekDFU7MAV1jKzWg">

this is probably because of unsupported fonts, the fonts im using dont have any chinese characters so thats why it doesnt looks empy

**Comment by ffs-akl** [comment]
all of chinese characters is in theme.conf,there is not any chinese character in the other files.
So, It probably is not the reason of chinese characters.
and the Original version have the same look as well.

**Comment by ffs-akl** [comment]
I tested the original version wiht` sddm-greeter-qt6 --test-mode  --theme  ` ,  it would fallback to default maui theme, and output an error messeage: org.ked.desktop not be installed.    Could this be the reason?

**Comment by syrupderg** [comment]
i dont get that error when i use that command, can you save your translations first then update my sddm theme? i made a few upgrades for it.

**Comment by knm100** [comment]
I checked the commit, Is this update all about face.icon?

**Comment by ffs-akl** [comment]
in the point of an user, the lastest rev is same as the original rev.

what environment did you run this theme in ?

**Comment by syrupderg** [comment]
> in the point of an user, the lastest rev is same as the original rev.

i did major changes to this sddm themes there is a lots of bug fixes etc.

> what environment did you run this theme in ?

i tried this theme both on xorg and wayland.

**Comment by ffs-akl** [comment]
> i did major changes to this sddm themes there is a lots of bug fixes etc.

I mean that the CaspOn didn't work and the button at the left of the session button didn't still  show up for me with the lastest rev

> i tried this theme both on xorg and wayland.

Would you tell me that what's your OS and DE?  plasma 6+Arch?

**Comment by ffs-akl** [comment]
I guess that the layout.qml component didn't get the information of keyboard in the virtual machine, So it has nothing to do with CapsOn.qml.
I tried to edit the text in layout.qml,  the text edited was displaied there.

**Comment by syrupderg** [comment]
> I guess that the layout.qml component didn't get the information of keyboard in the virtual machine, So it has nothing to do with CapsOn.qml. I tried to edit the text in layout.qml, the text edited was displaied there.

caps on warning message is buggy but not because of my theme, sddm or anything else, its because of virtual machine, you can also check windows to see that bug also happening.

as for the keyboard layout, i still dont know how to solve it because it worked on my pc and i also tested on a virtual box with fresh arch distro with kde but i didnt saw any of the bugs you told.

im on arch linux with linux-xen kernel 6.9.9 with kde plasma 6.1.2

**Comment by syrupderg** [comment]
if you dont have problems with changing texts im closing this issue (but if you do please re open the issue), for layout button not showing any text, open a new issue for it.

**Comment by ffs-akl** [comment]
Thank you for help.
