### ISSUE TITLE
Please install the required font error even tho its installed

### ISSUE THREAD

**Issue by Totallynotmwa** [birbkeks/win10-sddm-theme#2]
dont know why its happening

**Comment by syrupderg** [comment]
oops i coded to check if you have the font downloaded in the sddm theme's directory because i couldn't find a way to check if you have required fonts installed or not. 
```
/usr/share/sddm/themes/win10-sddm-theme/install.sh
```
use this command to run the sddm theme installer and install the required fonts from there

**Comment by syrupderg** [comment]
> dont know why its happening

fixed in [here](https://github.com/birbkeks/win11-sddm-theme/commit/fbf8bcb8bb934ee7c10ccb29b7034e89fb12a273), will update win 10 too
